[package]
name = "stignore-agent"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
stignore-lib = { path = "../lib" }
axum = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
axum-test = "17.3.0"
tempfile = "3.15.0"
