[agent]
port = 9002
name = "Agent 2"
base_path = "/tmp/media/agent2"
api_key = "6ba7b810-9dad-11d1-80b4-00c04fd430c8"

[[categories]]
id = "movies"
name = "Movies"
relative_path = "movies"

[[categories]]
id = "tv"
name = "TV Shows"
relative_path = "tv"
