[agent]
port = 9003
name = "Agent 3"
base_path = "/tmp/media/agent3"
api_key = "6ba7b811-9dad-11d1-80b4-00c04fd430c8"

[[categories]]
id = "movies"
name = "Movies"
relative_path = "movies"

[[categories]]
id = "tv"
name = "TV Shows"
relative_path = "tv"
